<?php
require 'csrf.php'; 
require 'auth.php';
require 'access_control.php';


session_start();
if (!isset($_SESSION["admin_logged_in"])) {
    header("Location: admin_login.php");
        exit;
        }
        require 'config.php';
        $message = '';

        if ($_SERVER["REQUEST_METHOD"] == "POST") {
            $fullname = trim($_POST['fullname']);
                $username = trim($_POST['username']);
                    $password = trim($_POST['password']);
                        $account_type = trim($_POST['account_type']);

                            if ($fullname === "" || $username === "" || $password === "" || $account_type === "") {
                                    $message = "يرجى ملء جميع الحقول.";
                                        } else {
                                                // منع حساب الوكيل من إضافة حساب وكيل آخر
                                                        if ($account_type === 'agent' && isset($_SESSION['account_type']) && $_SESSION['account_type'] === 'agent') {
                                                                    $message = "لا يمكنك إضافة حساب وكيل آخر.";
                                                                            } else {
                                                                                        // التحقق من تكرار اسم المستخدم
                                                                                                    $stmt = $pdo->prepare("SELECT id FROM users WHERE username = ?");
                                                                                                                $stmt->execute([$username]);
                                                                                                                            if ($stmt->fetch()) {
                                                                                                                                            $message = "اسم المستخدم موجود بالفعل.";
                                                                                                                                                        } else {
                                                                                                                                                                        $hashed_password = password_hash($password, PASSWORD_DEFAULT);
                                                                                                                                                                                        $encrypted_password = openssl_encrypt($password, 'AES-256-CBC', ENCRYPTION_KEY, 0, ENCRYPTION_IV);
                                                                                                                                                                                                        // تأكد من أن جدول users يحتوي على عمود account_type
                                                                                                                                                                                                                        $stmt = $pdo->prepare("INSERT INTO users (fullname, username, password, password_enc, account_type) VALUES (?, ?, ?, ?, ?)");
                                                                                                                                                                                                                                        if ($stmt->execute([$fullname, $username, $hashed_password, $encrypted_password, $account_type])) {
                                                                                                                                                                                                                                                            $message = "تم إضافة المستخدم بنجاح.";
                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                $message = "حدث خطأ أثناء إضافة المستخدم.";
                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                        include 'header.php';
                                                                                                                                                                                                                                                                                                                                        ?>
                                                                                                                                                                                                                                                                                                                                        <div class="card shadow-sm mb-4">
                                                                                                                                                                                                                                                                                                                                          <div class="card-body">
                                                                                                                                                                                                                                                                                                                                                <h2 class="card-title text-center mb-3">إضافة مستخدم جديد</h2>
                                                                                                                                                                                                                                                                                                                                                      <?php if ($message): ?>
                                                                                                                                                                                                                                                                                                                                                                <div class="alert alert-info text-center"><?php echo $message; ?></div>
                                                                                                                                                                                                                                                                                                                                                                      <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                            <form method="post">
                                                                                                                                                                                                                                                                                                                                                                                      <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                    <label class="form-label">الاسم الكامل</label>
                                                                                                                                                                                                                                                                                                                                                                                                                  <input type="text" name="fullname" class="form-control" placeholder="أدخل الاسم الكامل" required>
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label class="form-label">اسم المستخدم</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input type="text" name="username" class="form-control" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label class="form-label">كلمة المرور</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input type="password" name="password" class="form-control" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label class="form-label">نوع الحساب</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <select name="account_type" class="form-control" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="agent">الوكيل</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="normal" selected>مستخدم عادي</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option value="viewer">مشاهد</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div class="d-grid gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button type="submit" class="btn btn-primary btn-custom">إضافة المستخدم</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <?php include 'footer.php'; ?>