<?php
require 'csrf.php'; 
require 'auth.php';
require 'access_control.php';


session_start();
if (!isset($_SESSION["admin_logged_in"])) {
    header("Location: admin_login.php");
        exit;
        }
        $pageTitle = "أدوات الإدارة";
        require 'config.php';
        include 'header.php';
        ?>
        <div class="card shadow-sm mb-4">
          <div class="card-body text-center">
              <h2 class="card-title mb-3">
                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 16 16" fill="currentColor">
                            <path d="M8 4.754a3.246 3.246 0 1 0 0 5.492 3.246 3.246 0 0 0 0-5.492zM5.754 8a2.246 2.246 0 1 1 4.492 0 2.246 2.246 0 0 1-4.492 0z"/>
                                    <path d="M9.796 1.343c-.527-1.79-3.065-1.79-3.592 0l-.094.319a.873.873 0 0 1-1.255.52l-.292-.16c-1.64-.893-3.433.902-2.54 2.541l.159.292a.873.873 0 0 1-.52 1.255l-.319.094c-1.79.527-1.79 3.065 0 3.592l.319.094a.873.873 0 0 1 .52 1.255l-.16.292c-.893 1.64.902 3.433 2.541 2.54l.292-.159a.873.873 0 0 1 1.255.52l.094.319c.527 1.79 3.065 1.79 3.592 0l.094-.319a.873.873 0 0 1 1.255-.52l.292.16c1.64.893 3.433-.902 2.54-2.541l-.159-.292a.873.873 0 0 1 .52-1.255l.319-.094c1.79-.527 1.79-3.065 0-3.592l-.319-.094a.873.873 0 0 1-.52-1.255l.16-.292c.893-1.64-.902-3.433-2.541-2.54l-.292.159a.873.873 0 0 1-1.255-.52l-.094-.319zm-2.633.283c.246-.835 1.428-.835 1.674 0l.094.319a1.873 1.873 0 0 0 2.693 1.115l.291-.16c.764-.416 1.6.42 1.184 1.185l-.159.292a1.873 1.873 0 0 0 1.116 2.694l.318.094c.835.246.835 1.428 0 1.674l-.318.094a1.873 1.873 0 0 0-1.116 2.694l.159.292c.416.764-.42 1.6-1.184 1.184l-.291-.16a1.873 1.873 0 0 0-2.693 1.115l-.094.319c-.246.835-1.428.835-1.674 0l-.094-.319a1.873 1.873 0 0 0-2.693-1.115l-.292.16c-.764.416-1.6-.42-1.184-1.184l.159-.292a1.873 1.873 0 0 0-1.116-2.694l-.318-.094c-.835-.246-.835-1.428 0-1.674l.318-.094a1.873 1.873 0 0 0 1.116-2.694l-.159-.292c-.416-.764.42-1.6 1.184-1.184l.292.16a1.873 1.873 0 0 0 2.693-1.115l.094-.319z"/>
                                          </svg>
                                                أدوات الإدارة
                                                    </h2>
                                                        <div class="d-grid gap-2">
                                                              <a href="manage_centers.php" class="btn btn-danger btn-custom" title="إدارة المراكز">
                                                                      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-building" viewBox="0 0 16 16">
                                                                                <path d="M8.354.146a.5.5 0 0 0-.708 0l-7 7A.5.5 0 0 0 1 7.5V15h5v-4h4v4h5V7.5a.5.5 0 0 0-.146-.354l-7-7zM2 8.5V14h3V8.5H2zm4 0V14h3V8.5H6zm4 0V14h3V8.5h-3z"/>
                                                                                        </svg>
                                                                                                إدارة المراكز
                                                                                                      </a>
                                                                                                            <a href="manage_candidates.php" class="btn btn-warning btn-custom" title="إدارة المرشحين">
                                                                                                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
                                                                                                                              <path d="M13 7c0-1.657-1.343-3-3-3S7 5.343 7 7s1.343 3 3 3 3-1.343 3-3zM2 7a3 3 0 1 1 6 0 3 3 0 0 1-6 0z"/>
                                                                                                                                      </svg>
                                                                                                                                              إدارة المرشحين
                                                                                                                                                    </a>
                                                                                                                                                          <a href="manage_accounts.php" class="btn btn-secondary btn-custom" title="إدارة الحسابات">
                                                                                                                                                                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-check-fill" viewBox="0 0 16 16">
                                                                                                                                                                            <path d="M15.854 5.146a.5.5 0 0 1 0 .708l-2.5 2.5a.5.5 0 0 1-.708 0L11 7.707l-.646.647a.5.5 0 1 1-.708-.708l1-1a.5.5 0 0 1 .708 0l1.5 1.5a.5.5 0 0 1 0 .708l-2 2a.5.5 0 0 1-.708 0l-2-2a.5.5 0 0 1 0-.708L9 5.293l.646-.647a.5.5 0 0 1 .708.708l-1 1a.5.5 0 0 1 0 .708l1.5-1.5a.5.5 0 0 1 .708 0l2 2z"/>
                                                                                                                                                                                      <path d="M2 13s-1 0-1-1c0-1.105.672-2 2-2h6c1.328 0 2 .895 2 2 0 1-1 1-1 1H2z"/>
                                                                                                                                                                                              </svg>
                                                                                                                                                                                                      إدارة الحسابات
                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                  <a href="add_user.php" class="btn btn-success btn-custom" title="إضافة مستخدم جديد">
                                                                                                                                                                                                                          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 16 16">
                                                                                                                                                                                                                                    <path d="M1 14s-1 0-1-1 1-4 8-4 8 3 8 4-1 1-1 1H1zm11-9a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                                                                                                                                                                                                                              <path fill-rule="evenodd" d="M15 6.5a.5.5 0 0 1-.5.5H13v1.5a.5.5 0 0 1-1 0V7H10.5a.5.5 0 0 1 0-1H12V4.5a.5.5 0 0 1 1 0V6h1.5a.5.5 0 0 1 .5.5z"/>
                                                                                                                                                                                                                                                      </svg>
                                                                                                                                                                                                                                                              إضافة مستخدم جديد
                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                          <a href="upload_csv.php" class="btn btn-info btn-custom" title="رفع CSV">
                                                                                                                                                                                                                                                                                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-upload" viewBox="0 0 16 16">
                                                                                                                                                                                                                                                                                            <path d="M.5 9.9v3.6A1.5 1.5 0 0 0 2 15h12a1.5 1.5 0 0 0 1.5-1.5V9.9a.5.5 0 0 0-1 0v3.6a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5V9.9a.5.5 0 0 0-1 0z"/>
                                                                                                                                                                                                                                                                                                      <path d="M7.646 1.646a.5.5 0 0 1 .708 0l3.5 3.5a.5.5 0 1 1-.708.708L8.5 2.207V9.5a.5.5 0 0 1-1 0V2.207L4.854 5.854a.5.5 0 1 1-.708-.708l3.5-3.5z"/>
                                                                                                                                                                                                                                                                                                              </svg>
                                                                                                                                                                                                                                                                                                                      رفع CSV
                                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                                                  <!-- حفظ الإعدادات الأصلية: عرض أزرار إضافة المركز والمرشح كما كانت -->
                                                                                                                                                                                                                                                                                                                                        <a href="add_center.php" class="btn btn-warning btn-custom" title="إضافة مركز">
                                                                                                                                                                                                                                                                                                                                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-plus-square-fill" viewBox="0 0 16 16">
                                                                                                                                                                                                                                                                                                                                                          <path d="M16 14V2a2 2 0 0 0-2-2H2A2 2 0 0 0 0 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2zm-8-5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2v2a.5.5 0 0 1-1 0v-2h-2a.5.5 0 0 1 0-1h2v-2z"/>
                                                                                                                                                                                                                                                                                                                                                                  </svg>
                                                                                                                                                                                                                                                                                                                                                                          إضافة مركز
                                                                                                                                                                                                                                                                                                                                                                                </a>
                                                                                                                                                                                                                                                                                                                                                                                      <a href="add_candidate.php" class="btn btn-success btn-custom" title="إضافة مرشح">
                                                                                                                                                                                                                                                                                                                                                                                              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 16 16">
                                                                                                                                                                                                                                                                                                                                                                                                        <path d="M1 14s-1 0-1-1 1-4 8-4 8 3 8 4-1 1-1 1H1zm11-9a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                                                                                                                                                                                                                                                                                                                                                                                                  <path fill-rule="evenodd" d="M15 6.5a.5.5 0 0 1-.5.5H13v1.5a.5.5 0 0 1-1 0V7H10.5a.5.5 0 0 1 0-1H12V4.5a.5.5 0 0 1 1 0V6h1.5a.5.5 0 0 1 .5.5z"/>
                                                                                                                                                                                                                                                                                                                                                                                                                          </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                  إضافة مرشح
                                                                                                                                                                                                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <a href="log.php" class="btn btn-info btn-custom" title="عرض السجل">
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-clipboard-check" viewBox="0 0 16 16">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <path fill-rule="evenodd" d="M10.854 5.146a.5.5 0 0 0-.708 0L7.5 7.793 6.354 6.646a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0 0-.708z"/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <path d="M4 1.5A1.5 1.5 0 0 0 2.5 3h-1A1.5 1.5 0 0 0 0 4.5v9A1.5 1.5 0 0 0 1.5 15h13A1.5 1.5 0 0 0 16 13.5v-9A1.5 1.5 0 0 0 14.5 3h-1A1.5 1.5 0 0 0 12 1.5H4zm0 1h8a.5.5 0 0 1 .5.5v1h-9V3a.5.5 0 0 1 .5-.5z"/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          عرض السجل
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a href="admin_logout.php" class="btn btn-outline-danger btn-custom" title="تسجيل الخروج">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <path fill-rule="evenodd" d="M6.146 11.354a.5.5 0 0 1 .708 0L10 14.5V1.5L6.854 4.646a.5.5 0 1 1-.708-.708l3-3a.5.5 0 0 1 .708 0l3 3a.5.5 0 1 1-.708.708L11 1.207V14.5a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5V1.207L6.854 4.646a.5.5 0 0 1-.708-.708l3-3z"/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        تسجيل الخروج
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <!-- قسم إدارة الموقع - يظهر فقط للمسؤول -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php if(isset($_SESSION['account_type']) && $_SESSION['account_type'] === 'admin'): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="card shadow-sm mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div class="card-body text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2 class="card-title mb-3">إدارة الموقع</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div class="d-grid gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <!-- الزر الذي ينقل المستخدم إلى صفحة إدارة الموقع -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a href="site_management.php" class="btn btn-dark btn-custom" title="إدارة الموقع">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <i class="fa-solid fa-cog"></i> إدارة الموقع
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <?php endif; ?>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div class="text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a href="index.php" class="btn btn-primary btn-custom" title="العودة إلى الصفحة الرئيسية">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <path d="M6.5 14.5v-4h3v4h5v-6h1L8 0 0 8.5h1v6z"/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  الرئيسية
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php include 'footer.php'; ?>