<?php
require 'csrf.php'; 
session_start();
require 'config.php';

$error = "";


if ($_SERVER["REQUEST_METHOD"] === "POST") {
    $username = trim($_POST["username"]);
        $password = trim($_POST["password"]);
            // بيانات حساب الأدمن الثابتة
                $adminUser = "admin";
                    $adminPass = "admin123";

                        if ($username === $adminUser && $password === $adminPass) {
                                // جلب صف المستخدم (إن وُجد) مع fullname
                                        $stmt = $pdo->prepare("
                                                    SELECT id, fullname, current_session_id
                                                                FROM users
                                                                            WHERE username = ?
                                                                                    ");
                                                                                            $stmt->execute([$username]);
                                                                                                    $user = $stmt->fetch(PDO::FETCH_ASSOC);

                                                                                                            // إذا الحساب موجود في users، نمنع الجلسة المزدوجة
                                                                                                                    if ($user && !empty($user['current_session_id'])) {
                                                                                                                                $error = "هذا الحساب مُسجّل دخول بالفعل من جهاز آخر. الرجاء تسجيل الخروج أولاً.";
                                                                                                                                        } else {
                                                                                                                                                    session_regenerate_id(true);
                                                                                                                                                                $_SESSION["admin_logged_in"] = true;
                                                                                                                                                                            // تخزين الاسم الكامل في الجلسة
                                                                                                                                                                                        if ($user && !empty($user['fullname'])) {
                                                                                                                                                                                                        $_SESSION['fullname'] = $user['fullname'];
                                                                                                                                                                                                                        // تحديث session_id في قاعدة البيانات
                                                                                                                                                                                                                                        $stmt2 = $pdo->prepare("UPDATE users SET current_session_id = ? WHERE id = ?");
                                                                                                                                                                                                                                                        $stmt2->execute([session_id(), $user['id']]);
                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                    $_SESSION['fullname'] = "الأدمن";
                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                            header("Location: admin_tools.php");
                                                                                                                                                                                                                                                                                                                        exit;
                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                            $error = "بيانات اعتماد الأدمن غير صحيحة.";
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                include 'header.php';
                                                                                                                                                                                                                                                                                                                                                ?>
                                                                                                                                                                                                                                                                                                                                                <div class="card shadow-sm">
                                                                                                                                                                                                                                                                                                                                                  <div class="card-body">
                                                                                                                                                                                                                                                                                                                                                        <h2 class="card-title text-center mb-3">تسجيل دخول الأدمن</h2>
                                                                                                                                                                                                                                                                                                                                                              <?php if ($error): ?>
                                                                                                                                                                                                                                                                                                                                                                        <div class="alert alert-danger text-center"><?php echo $error; ?></div>
                                                                                                                                                                                                                                                                                                                                                                              <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                    <form method="POST">
                                                                                                                                                                                                                                                                                                                                                                                              <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                            <label class="form-label">اسم المستخدم</label>
                                                                                                                                                                                                                                                                                                                                                                                                                          <input type="text" name="username" class="form-control" placeholder="ادخل اسم المستخدم" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label class="form-label">كلمة المرور</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input type="password" name="password" class="form-control" placeholder="ادخل كلمة المرور" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div class="d-grid gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button type="submit" class="btn btn-primary btn-custom">تسجيل الدخول</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <?php include 'footer.php'; ?><?php
session_start();
require 'config.php';
$error = "";

if ($_SERVER["REQUEST_METHOD"] === "POST") {
    $username = trim($_POST["username"]);
        $password = trim($_POST["password"]);
            // بيانات حساب الأدمن الثابتة
                $adminUser = "admin";
                    $adminPass = "admin123";

                        if ($username === $adminUser && $password === $adminPass) {
                                // جلب صف المستخدم (إن وُجد) مع fullname
                                        $stmt = $pdo->prepare("
                                                    SELECT id, fullname, current_session_id
                                                                FROM users
                                                                            WHERE username = ?
                                                                                    ");
                                                                                            $stmt->execute([$username]);
                                                                                                    $user = $stmt->fetch(PDO::FETCH_ASSOC);

                                                                                                            // إذا الحساب موجود في users، نمنع الجلسة المزدوجة
                                                                                                                    if ($user && !empty($user['current_session_id'])) {
                                                                                                                                $error = "هذا الحساب مُسجّل دخول بالفعل من جهاز آخر. الرجاء تسجيل الخروج أولاً.";
                                                                                                                                        } else {
                                                                                                                                                    session_regenerate_id(true);
                                                                                                                                                                $_SESSION["admin_logged_in"] = true;
                                                                                                                                                                            // تخزين الاسم الكامل في الجلسة
                                                                                                                                                                                        if ($user && !empty($user['fullname'])) {
                                                                                                                                                                                                        $_SESSION['fullname'] = $user['fullname'];
                                                                                                                                                                                                                        // تحديث session_id في قاعدة البيانات
                                                                                                                                                                                                                                        $stmt2 = $pdo->prepare("UPDATE users SET current_session_id = ? WHERE id = ?");
                                                                                                                                                                                                                                                        $stmt2->execute([session_id(), $user['id']]);
                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                    $_SESSION['fullname'] = "الأدمن";
                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                            header("Location: admin_tools.php");
                                                                                                                                                                                                                                                                                                                        exit;
                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                            $error = "بيانات اعتماد الأدمن غير صحيحة.";
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                include 'header.php';
                                                                                                                                                                                                                                                                                                                                                ?>
                                                                                                                                                                                                                                                                                                                                                <div class="card shadow-sm">
                                                                                                                                                                                                                                                                                                                                                  <div class="card-body">
                                                                                                                                                                                                                                                                                                                                                        <h2 class="card-title text-center mb-3">تسجيل دخول الأدمن</h2>
                                                                                                                                                                                                                                                                                                                                                              <?php if ($error): ?>
                                                                                                                                                                                                                                                                                                                                                                        <div class="alert alert-danger text-center"><?php echo $error; ?></div>
                                                                                                                                                                                                                                                                                                                                                                              <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                    <form method="POST">
                                                                                                                                                                                                                                                                                                                                                                                              <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                            <label class="form-label">اسم المستخدم</label>
                                                                                                                                                                                                                                                                                                                                                                                                                          <input type="text" name="username" class="form-control" placeholder="ادخل اسم المستخدم" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label class="form-label">كلمة المرور</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input type="password" name="password" class="form-control" placeholder="ادخل كلمة المرور" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div class="d-grid gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button type="submit" class="btn btn-primary btn-custom">تسجيل الدخول</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <?php include 'footer.php'; ?><?php
session_start();
require 'config.php';
$error = "";

if ($_SERVER["REQUEST_METHOD"] === "POST") {
    $username = trim($_POST["username"]);
        $password = trim($_POST["password"]);
            // بيانات حساب الأدمن الثابتة
                $adminUser = "admin";
                    $adminPass = "admin123";

                        if ($username === $adminUser && $password === $adminPass) {
                                // جلب صف المستخدم (إن وُجد) مع fullname
                                        $stmt = $pdo->prepare("
                                                    SELECT id, fullname, current_session_id
                                                                FROM users
                                                                            WHERE username = ?
                                                                                    ");
                                                                                            $stmt->execute([$username]);
                                                                                                    $user = $stmt->fetch(PDO::FETCH_ASSOC);

                                                                                                            // إذا الحساب موجود في users، نمنع الجلسة المزدوجة
                                                                                                                    if ($user && !empty($user['current_session_id'])) {
                                                                                                                                $error = "هذا الحساب مُسجّل دخول بالفعل من جهاز آخر. الرجاء تسجيل الخروج أولاً.";
                                                                                                                                        } else {
                                                                                                                                                    session_regenerate_id(true);
                                                                                                                                                                $_SESSION["admin_logged_in"] = true;
                                                                                                                                                                            // تخزين الاسم الكامل في الجلسة
                                                                                                                                                                                        if ($user && !empty($user['fullname'])) {
                                                                                                                                                                                                        $_SESSION['fullname'] = $user['fullname'];
                                                                                                                                                                                                                        // تحديث session_id في قاعدة البيانات
                                                                                                                                                                                                                                        $stmt2 = $pdo->prepare("UPDATE users SET current_session_id = ? WHERE id = ?");
                                                                                                                                                                                                                                                        $stmt2->execute([session_id(), $user['id']]);
                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                    $_SESSION['fullname'] = "الأدمن";
                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                            header("Location: admin_tools.php");
                                                                                                                                                                                                                                                                                                                        exit;
                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                            $error = "بيانات اعتماد الأدمن غير صحيحة.";
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                include 'header.php';
                                                                                                                                                                                                                                                                                                                                                ?>
                                                                                                                                                                                                                                                                                                                                                <div class="card shadow-sm">
                                                                                                                                                                                                                                                                                                                                                  <div class="card-body">
                                                                                                                                                                                                                                                                                                                                                        <h2 class="card-title text-center mb-3">تسجيل دخول الأدمن</h2>
                                                                                                                                                                                                                                                                                                                                                              <?php if ($error): ?>
                                                                                                                                                                                                                                                                                                                                                                        <div class="alert alert-danger text-center"><?php echo $error; ?></div>
                                                                                                                                                                                                                                                                                                                                                                              <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                    <form method="POST">
                                                                                                                                                                                                                                                                                                                                                                                              <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                            <label class="form-label">اسم المستخدم</label>
                                                                                                                                                                                                                                                                                                                                                                                                                          <input type="text" name="username" class="form-control" placeholder="ادخل اسم المستخدم" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label class="form-label">كلمة المرور</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input type="password" name="password" class="form-control" placeholder="ادخل كلمة المرور" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div class="d-grid gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button type="submit" class="btn btn-primary btn-custom">تسجيل الدخول</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <?php include 'footer.php'; ?><?php
session_start();
require 'config.php';
$error = "";

if ($_SERVER["REQUEST_METHOD"] === "POST") {
    $username = trim($_POST["username"]);
        $password = trim($_POST["password"]);
            // بيانات حساب الأدمن الثابتة
                $adminUser = "admin";
                    $adminPass = "admin123";

                        if ($username === $adminUser && $password === $adminPass) {
                                // جلب صف المستخدم (إن وُجد) مع fullname
                                        $stmt = $pdo->prepare("
                                                    SELECT id, fullname, current_session_id
                                                                FROM users
                                                                            WHERE username = ?
                                                                                    ");
                                                                                            $stmt->execute([$username]);
                                                                                                    $user = $stmt->fetch(PDO::FETCH_ASSOC);

                                                                                                            // إذا الحساب موجود في users، نمنع الجلسة المزدوجة
                                                                                                                    if ($user && !empty($user['current_session_id'])) {
                                                                                                                                $error = "هذا الحساب مُسجّل دخول بالفعل من جهاز آخر. الرجاء تسجيل الخروج أولاً.";
                                                                                                                                        } else {
                                                                                                                                                    session_regenerate_id(true);
                                                                                                                                                                $_SESSION["admin_logged_in"] = true;
                                                                                                                                                                            // تخزين الاسم الكامل في الجلسة
                                                                                                                                                                                        if ($user && !empty($user['fullname'])) {
                                                                                                                                                                                                        $_SESSION['fullname'] = $user['fullname'];
                                                                                                                                                                                                                        // تحديث session_id في قاعدة البيانات
                                                                                                                                                                                                                                        $stmt2 = $pdo->prepare("UPDATE users SET current_session_id = ? WHERE id = ?");
                                                                                                                                                                                                                                                        $stmt2->execute([session_id(), $user['id']]);
                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                    $_SESSION['fullname'] = "الأدمن";
                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                            header("Location: admin_tools.php");
                                                                                                                                                                                                                                                                                                                        exit;
                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                            $error = "بيانات اعتماد الأدمن غير صحيحة.";
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                include 'header.php';
                                                                                                                                                                                                                                                                                                                                                ?>
                                                                                                                                                                                                                                                                                                                                                <div class="card shadow-sm">
                                                                                                                                                                                                                                                                                                                                                  <div class="card-body">
                                                                                                                                                                                                                                                                                                                                                        <h2 class="card-title text-center mb-3">تسجيل دخول الأدمن</h2>
                                                                                                                                                                                                                                                                                                                                                              <?php if ($error): ?>
                                                                                                                                                                                                                                                                                                                                                                        <div class="alert alert-danger text-center"><?php echo $error; ?></div>
                                                                                                                                                                                                                                                                                                                                                                              <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                    <form method="POST">
                                                                                                                                                                                                                                                                                                                                                                                              <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                            <label class="form-label">اسم المستخدم</label>
                                                                                                                                                                                                                                                                                                                                                                                                                          <input type="text" name="username" class="form-control" placeholder="ادخل اسم المستخدم" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label class="form-label">كلمة المرور</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input type="password" name="password" class="form-control" placeholder="ادخل كلمة المرور" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div class="d-grid gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button type="submit" class="btn btn-primary btn-custom">تسجيل الدخول</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <?php include 'footer.php'; ?>