<?php
require 'csrf.php'; 
require 'auth.php';
require 'access_control.php';
$pageTitle = "رفع CSV للمرشحين";
require 'config.php';
$message = '';

if ($_SERVER["REQUEST_METHOD"] === "POST") {
    if (isset($_FILES['csv_file']) && $_FILES['csv_file']['error'] === UPLOAD_ERR_OK) {
            $fileTmpPath = $_FILES['csv_file']['tmp_name'];
                    $fileName = $_FILES['csv_file']['name'];
                            $extension = strtolower(pathinfo($fileName, PATHINFO_EXTENSION));
                                    if ($extension === 'csv') {
                                                $handle = fopen($fileTmpPath, 'r');
                                                            if ($handle !== false) {
                                                                            $rowCount = 0;
                                                                                            while (($data = fgetcsv($handle, 1000, ',')) !== false) {
                                                                                                                $candidateName = trim($data[0]);
                                                                                                                                    if ($candidateName !== '') {
                                                                                                                                                            // تحقق من عدم وجود المرشح مسبقاً
                                                                                                                                                                                    $stmt = $pdo->prepare("SELECT id FROM candidates WHERE candidate_name = ?");
                                                                                                                                                                                                            $stmt->execute([$candidateName]);
                                                                                                                                                                                                                                    if (!$stmt->fetch()) {
                                                                                                                                                                                                                                                                $insert = $pdo->prepare("INSERT INTO candidates (candidate_name) VALUES (?)");
                                                                                                                                                                                                                                                                                            $insert->execute([$candidateName]);
                                                                                                                                                                                                                                                                                                                        $rowCount++;
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                    fclose($handle);
                                                                                                                                                                                                                                                                                                                                                                                                                    $message = "تم إضافة $rowCount مرشح/مرشحين بنجاح.";
                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                $message = "تعذر فتح ملف CSV.";
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $message = "يرجى رفع ملف بصيغة CSV فقط.";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $message = "حدث خطأ أثناء رفع الملف.";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        include 'header.php';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ?><div class="card shadow-sm my-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div class="card-body">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 class="card-title text-center mb-3">رفع CSV للمرشحين</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <?php if ($message): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="alert alert-info text-center"><?php echo $message; ?></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <form method="POST" enctype="multipart/form-data">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label class="form-label">اختر ملف CSV للمَرَشّحِين</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input type="file" name="csv_file" class="form-control" accept=".csv" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div class="d-grid gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button type="submit" class="btn btn-success btn-custom">رفع CSV للمرشحين</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div class="text-center mt-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href="upload.php" class="btn btn-secondary btn-custom">عودة</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php include 'footer.php'; ?>