<?php
session_start();
require 'csrf.php';
require 'auth.php';
require 'config.php';
$pageTitle = "لوحة التحكّم";
include 'header.php';

// استعلامات أساسية
$totalCenters       = (int)$pdo->query("SELECT COUNT(*) FROM centers")->fetchColumn();
$totalStations      = (int)$pdo->query("SELECT COUNT(*) FROM stations")->fetchColumn();
$totalCandidates    = (int)$pdo->query("SELECT COUNT(*) FROM candidates")->fetchColumn();
$totalEnteredVotes  = (int)$pdo->query("SELECT SUM(vote_count) FROM votes")->fetchColumn();

// حساب المراكز المكتملة
$completeCenters = (int)$pdo->query(
    "SELECT COUNT(DISTINCT s.center_id) FROM stations s
         JOIN votes v ON s.id = v.station_id
              GROUP BY s.id
                   HAVING COUNT(v.candidate_id) = $totalCandidates"
                   )->fetchColumn();

                   // نسبة إدخال الأصوات
                   $maxPossibleVotes = $totalStations * $totalCandidates;
                   $entryPercentage  = $maxPossibleVotes > 0 ? round(($totalEnteredVotes / $maxPossibleVotes) * 100, 2) : 0;

                   // أعلى 5 مرشحين حسب الأصوات
                   $topCandidatesStmt = $pdo->query(
                       "SELECT c.candidate_name, SUM(v.vote_count) as votes
                            FROM votes v
                                 JOIN candidates c ON v.candidate_id = c.id
                                      GROUP BY c.id
                                           ORDER BY votes DESC
                                                LIMIT 5"
                                                );
                                                $topCandidates = $topCandidatesStmt->fetchAll(PDO::FETCH_ASSOC);

                                                // آخر الأنشطة
                                                $logFile    = 'logs.txt';
                                                $activities = [];
                                                if (file_exists($logFile)) {
                                                    $lines      = array_slice(file($logFile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES), -5);
                                                        $activities = array_reverse($lines);
                                                        }

                                                        // طابع زمني لآخر تحديث
                                                        $lastUpdate = date('Y-m-d H:i:s');
                                                        ?>

                                                        <style>
                                                        /* ستايل متقدم للوحة التحكم */
                                                        .dashboard-card {
                                                            background: rgba(255, 255, 255, 0.1) !important;
                                                                border-radius: 1rem;
                                                                    backdrop-filter: blur(12px);
                                                                        border: 1px solid rgba(255,255,255,0.2);
                                                                            transition: transform 0.2s;
                                                                            }
                                                                            .dashboard-card:hover { transform: translateY(-5px); }
                                                                            .dashboard-icon { font-size: 2.5rem; opacity: 0.85; }
                                                                            .chart-container {
                                                                                background: rgba(255,255,255,0.08) !important;
                                                                                    border-radius: 1rem;
                                                                                        backdrop-filter: blur(12px);
                                                                                            padding: 1.5rem;
                                                                                            }
                                                                                            .activities-list {
                                                                                                background: rgba(255,255,255,0.05) !important;
                                                                                                    border-radius: 1rem;
                                                                                                        backdrop-filter: blur(12px);
                                                                                                            padding: 1rem;
                                                                                                            }
                                                                                                            .activities-list li { background: transparent; border: none; color: #eee; }
                                                                                                            .last-update { font-size: 0.9rem; color: #ccc; }
                                                                                                            </style>

                                                                                                            <div class="container my-5">
                                                                                                              <div class="d-flex justify-content-between align-items-center mb-3">
                                                                                                                  <h1 class="text-white">لوحة التحكّم</h1>
                                                                                                                      <span class="last-update">آخر تحديث: <?php echo $lastUpdate; ?></span>
                                                                                                                        </div>

                                                                                                                          <div class="row g-4 mb-4">
                                                                                                                              <div class="col-lg-3 col-md-6">
                                                                                                                                    <div class="card dashboard-card text-white shadow h-100 border-info p-3">
                                                                                                                                            <div class="d-flex align-items-center">
                                                                                                                                                      <i class="fa-solid fa-building dashboard-icon me-3 text-info"></i>
                                                                                                                                                                <div>
                                                                                                                                                                            <h6>إجمالي المراكز</h6>
                                                                                                                                                                                        <h3><?php echo $totalCenters; ?></h3>
                                                                                                                                                                                                  </div>
                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                        <div class="col-lg-3 col-md-6">
                                                                                                                                                                                                                              <div class="card dashboard-card text-white shadow h-100 border-success p-3">
                                                                                                                                                                                                                                      <div class="d-flex align-items-center">
                                                                                                                                                                                                                                                <i class="fa-solid fa-check-circle dashboard-icon me-3 text-success"></i>
                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                      <h6>المراكز المكتملة</h6>
                                                                                                                                                                                                                                                                                  <h3><?php echo $completeCenters; ?></h3>
                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                  <div class="col-lg-3 col-md-6">
                                                                                                                                                                                                                                                                                                                        <div class="card dashboard-card text-white shadow h-100 border-warning p-3">
                                                                                                                                                                                                                                                                                                                                <div class="d-flex align-items-center">
                                                                                                                                                                                                                                                                                                                                          <i class="fa-solid fa-map-marker-alt dashboard-icon me-3 text-warning"></i>
                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                <h6>عدد المحطات</h6>
                                                                                                                                                                                                                                                                                                                                                                            <h3><?php echo $totalStations; ?></h3>
                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                            <div class="col-lg-3 col-md-6">
                                                                                                                                                                                                                                                                                                                                                                                                                  <div class="card dashboard-card text-white shadow h-100 border-danger p-3">
                                                                                                                                                                                                                                                                                                                                                                                                                          <div class="d-flex align-items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                    <i class="fa-solid fa-vote-yea dashboard-icon me-3 text-danger"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h6>إجمالي الأصوات</h6>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h3><?php echo $totalEnteredVotes; ?></h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div class="row g-4 mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div class="col-lg-4 col-md-12">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="chart-container shadow h-100">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h6 class="text-white mb-3">حالة المراكز</h6>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <canvas id="centersChart"></canvas>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div class="col-lg-4 col-md-12">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="chart-container shadow h-100">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h6 class="text-white mb-3">نسبة إدخال الأصوات</h6>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <canvas id="votesChart"></canvas>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div class="col-lg-4 col-md-12">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="chart-container shadow h-100">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h6 class="text-white mb-3">أعلى 5 مرشحين</h6>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <canvas id="topCandidatesChart"></canvas>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div class="activities-list shadow-lg mb-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h6 class="text-white mb-3"><i class="fa-solid fa-clock-rotate-left me-2"></i>آخر الأنشطة</h6>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <ul class="list-group list-group-flush">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php if ($activities): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php foreach ($activities as $line): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <li class="list-group-item">&bull; <?php echo htmlspecialchars($line); ?></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <?php endforeach; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php else: ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <li class="list-group-item text-center">لا توجد أنشطة حتى الآن.</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const centersData = [<?php echo $completeCenters; ?>, <?php echo $totalCenters - $completeCenters; ?>];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        new Chart(document.getElementById('centersChart'), { type: 'doughnut', data: { labels: ['مكتملة','غير مكتملة'], datasets: [{ data: centersData, backgroundColor: ['#198754','#6c757d'] }] }, options: { plugins: { legend: { labels: { color: '#fff' } } } } });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        new Chart(document.getElementById('votesChart'), { type: 'pie', data: { labels: ['مدخلة','متبقية'], datasets: [{ data: [<?php echo $totalEnteredVotes; ?>, <?php echo max(0,$maxPossibleVotes-$totalEnteredVotes); ?>], backgroundColor: ['#ffc107','#0d6efd'] }] }, options: { plugins: { legend: { labels: { color: '#fff' } } } } });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const topLabels = <?php echo json_encode(array_column($topCandidates,'candidate_name')); ?>;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const topVotes  = <?php echo json_encode(array_column($topCandidates,'votes')); ?>;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        new Chart(document.getElementById('topCandidatesChart'), { type: 'bar', data: { labels: topLabels, datasets: [{ label: 'الأصوات', data: topVotes, backgroundColor: '#0dcaf0' }] }, options: { scales: { y: { ticks: { color: '#fff' }, grid: { color: 'rgba(255,255,255,0.2)' } }, x: { ticks: { color: '#fff' }, grid: { display: false } } }, plugins: { legend: { display: false } } } });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </script>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?php include 'footer.php'; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        