<?php
require 'csrf.php'; 
require 'auth.php';
require 'access_control.php';
// تضمين مكتبة SheetJS (XLSX)
?>
<script src="https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js"></script>
<script>
  function exportToExcel() {
      // 1. أنشئ كتاب عمل جديد
          const wb = XLSX.utils.book_new();

              // **إضافة خاصية RTL لجعل الورقة تبدأ من اليمين لليسار**
                  wb.Workbook = wb.Workbook || {};
                      wb.Workbook.Views = wb.Workbook.Views || [];
                          wb.Workbook.Views[0] = wb.Workbook.Views[0] || {};
                              wb.Workbook.Views[0].RTL = true;

                                  // دالة لتطبيق التنسيق على خلايا الرأس (العناوين الرئيسية والجداول)
                                      const applyHeaderStyle = (ws, cellAddress) => {
                                            if (ws[cellAddress]) {
                                                    ws[cellAddress].s = {
                                                              font: { bold: true, size: 16, color: { rgb: "FFFFFF" } }, // خط عريض، حجم 16، لون أبيض
                                                                        fill: { patternType: "solid", fgColor: { rgb: "4CAF50" } }, // خلفية خضراء
                                                                                  alignment: { horizontal: "center", vertical: "middle" }, // توسيط أفقي وعمودي
                                                                                            border: {
                                                                                                        top: { style: "thin", color: { rgb: "000000" } },
                                                                                                                    bottom: { style: "thin", color: { rgb: "000000" } },
                                                                                                                                left: { style: "thin", color: { rgb: "000000" } },
                                                                                                                                            right: { style: "thin", color: { rgb: "000000" } },
                                                                                                                                                      },
                                                                                                                                                              };
                                                                                                                                                                    }
                                                                                                                                                                        };

                                                                                                                                                                            // دالة لتطبيق التنسيق على خلايا البيانات مع التوسيط
                                                                                                                                                                                const applyDataStyle = (ws, cellAddress) => {
                                                                                                                                                                                      if (ws[cellAddress]) {
                                                                                                                                                                                              ws[cellAddress].s = {
                                                                                                                                                                                                        font: { size: 12 },
                                                                                                                                                                                                                  alignment: { horizontal: "center", vertical: "middle" }, // توسيط أفقي وعمودي
                                                                                                                                                                                                                            border: {
                                                                                                                                                                                                                                        top: { style: "thin", color: { rgb: "D3D3D3" } },
                                                                                                                                                                                                                                                    bottom: { style: "thin", color: { rgb: "D3D3D3" } },
                                                                                                                                                                                                                                                                left: { style: "thin", color: { rgb: "D3D3D3" } },
                                                                                                                                                                                                                                                                            right: { style: "thin", color: { rgb: "D3D3D3" } },
                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                            // دالة لتطبيق تنسيق خاص لعناوين المراكز والمحطات
                                                                                                                                                                                                                                                                                                                const applyCenterStationHeaderStyle = (ws, cellAddress, bgColor) => {
                                                                                                                                                                                                                                                                                                                      if (ws[cellAddress]) {
                                                                                                                                                                                                                                                                                                                              ws[cellAddress].s = {
                                                                                                                                                                                                                                                                                                                                        font: { bold: true, size: 14, color: { rgb: "FFFFFF" } },
                                                                                                                                                                                                                                                                                                                                                  fill: { patternType: "solid", fgColor: { rgb: bgColor } }, // استخدام لون خلفية مخصص
                                                                                                                                                                                                                                                                                                                                                            alignment: { horizontal: "center", vertical: "middle" },
                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                  // دالة لتحديد عرض العمود
                                                                                                                                                                                                                                                                                                                                                                                      const setColumnWidth = (ws, columnIndex, width) => {
                                                                                                                                                                                                                                                                                                                                                                                            ws['!cols'] = ws['!cols'] || [];
                                                                                                                                                                                                                                                                                                                                                                                                  ws['!cols'][columnIndex] = { wch: width };
                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                          // 2. أنشئ ورقة عمل جديدة من جدول الملخص العام
                                                                                                                                                                                                                                                                                                                                                                                                              const summaryTable = document.querySelector('#export-area .card-body table');
                                                                                                                                                                                                                                                                                                                                                                                                                  const ws = XLSX.utils.table_to_sheet(summaryTable, { raw: true });
                                                                                                                                                                                                                                                                                                                                                                                                                      setColumnWidth(ws, 0, 30); // عرض عمود المرشح
                                                                                                                                                                                                                                                                                                                                                                                                                          setColumnWidth(ws, 1, 20); // عرض عمود عدد الأصوات

                                                                                                                                                                                                                                                                                                                                                                                                                              // تطبيق تنسيق على جميع خلايا جدول الملخص (الرأس والبيانات)
                                                                                                                                                                                                                                                                                                                                                                                                                                  summaryTable.querySelectorAll('th, td').forEach(cell => {
                                                                                                                                                                                                                                                                                                                                                                                                                                        const cellAddress = XLSX.utils.encode_cell({ r: cell.parentNode.rowIndex, c: cell.cellIndex });
                                                                                                                                                                                                                                                                                                                                                                                                                                              if (cell.tagName === 'TH') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      applyHeaderStyle(ws, cellAddress);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    applyDataStyle(ws, cellAddress);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  let currentRow = summaryTable.rows.length + 3; // نبدأ بعد الملخص بمسافة 3 صفوف

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // 3. لكل بطاقة مركز، أضف العنوان والجداول مع التنسيق
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          document.querySelectorAll('#centersContainer .card').forEach(card => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // (أ) إضافة عنوان المركز كسطر مستقل وتنسيقه مع دمج خليتين
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const centerName = card.querySelector('.card-header span').textContent.trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const centerCellAddress = XLSX.utils.encode_cell({ r: currentRow, c: 0 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  XLSX.utils.sheet_add_aoa(ws, [[centerName]], { origin: centerCellAddress });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        applyCenterStationHeaderStyle(ws, centerCellAddress, "007BFF"); // لون خلفية أزرق للمركز
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ws['!merges'] = (ws['!merges'] || []).concat([{ s: { r: currentRow, c: 0 }, e: { r: currentRow, c: 1 } }]); // دمج العمودين A و B
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ws['!rows'] = ws['!rows'] || [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ws['!rows'][currentRow] = { hpx: 35 }; // زيادة ارتفاع صف العنوان
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                currentRow++;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // (ب) جدول أصوات المرشحين داخل المركز
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const candTable = card.querySelector('table.table-bordered');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  XLSX.utils.sheet_add_dom(ws, candTable, { origin: { r: currentRow, c: 0 } });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        candTable.querySelectorAll('th, td').forEach(cell => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const cellAddress = XLSX.utils.encode_cell({ r: currentRow + cell.parentNode.rowIndex, c: cell.cellIndex });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (cell.tagName === 'TH') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  applyHeaderStyle(ws, cellAddress);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    applyDataStyle(ws, cellAddress);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (let i = 0; i < candTable.querySelectorAll('thead th').length; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setColumnWidth(ws, i, 25); // زيادة عرض أعمدة جدول المرشحين
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            currentRow += candTable.rows.length + 3; // إضافة مسافة 3 صفوف بعد الجدول

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // (ج) لكل جدول محطة (table-sm) ضمن البطاقة
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        card.querySelectorAll('table.table-sm').forEach((stationTable, idx) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // إضافة عنوان المحطة وتنسيقه مع دمج خليتين
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const stationHeader = card.querySelectorAll('.card-body h6')[idx].textContent.trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const stationCellAddress = XLSX.utils.encode_cell({ r: currentRow, c: 0 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        XLSX.utils.sheet_add_aoa(ws, [[stationHeader]], { origin: stationCellAddress });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                applyCenterStationHeaderStyle(ws, stationCellAddress, "6C757D"); // لون خلفية رمادي للمحطة
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ws['!merges'] = (ws['!merges'] || []).concat([{ s: { r: currentRow, c: 0 }, e: { r: currentRow, c: 1 } }]); // دمج العمودين A و B
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ws['!rows'] = ws['!rows'] || [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ws['!rows'][currentRow] = { hpx: 30 }; // زيادة ارتفاع صف العنوان
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                currentRow++;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // إضافة جدول أصوات المحطة
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                XLSX.utils.sheet_add_dom(ws, stationTable, { origin: { r: currentRow, c: 0 } });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        stationTable.querySelectorAll('th, td').forEach(cell => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const cellAddress = XLSX.utils.encode_cell({ r: currentRow + cell.parentNode.rowIndex, c: cell.cellIndex });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (cell.tagName === 'TH') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        applyHeaderStyle(ws, cellAddress);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              applyDataStyle(ws, cellAddress);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (let i = 0; i < stationTable.querySelectorAll('thead th').length; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setColumnWidth(ws, i, 20); // زيادة عرض أعمدة جدول المحطة
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  currentRow += stationTable.rows.length + 3; // إضافة مسافة 3 صفوف بعد الجدول
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 4. أضف الورقة إلى الكتاب وصدّر الملف
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    XLSX.utils.book_append_sheet(wb, ws, 'النتائج الكاملة');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        XLSX.writeFile(wb, 'نتائج_الانتخابات.xlsx');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          