<?php
require 'csrf.php';
require 'auth.php';
$pageTitle = "لوحة التحكم";
require 'config.php';
include 'header.php';
?>
<style>
  .hero-section {
      padding: 80px 15px;
          text-align: center;
              color: #fff;
                  position: relative;
                    }
                      .hero-section::before {
                          content: '';
                              position: absolute;
                                  top: 0;
                                      left: 0;
                                          width: 100%;
                                              height: 100%;
                                                  background: rgba(0,0,0,0.35);
                                                      z-index: 0;
                                                        }
                                                          .hero-content {
                                                              position: relative;
                                                                  z-index: 1;
                                                                    }
                                                                      .button-area {
                                                                          margin-top: 20px;
                                                                              display: flex;
                                                                                  flex-wrap: wrap;
                                                                                      justify-content: center;
                                                                                          gap: 15px;
                                                                                            }
                                                                                              .button-area a {
                                                                                                  text-transform: uppercase;
                                                                                                      padding: 12px 25px;
                                                                                                          font-size: 1.1rem;
                                                                                                              border-radius: 30px;
                                                                                                                  text-decoration: none;
                                                                                                                      color: #fff;
                                                                                                                          transition: all 0.3s ease;
                                                                                                                            }
                                                                                                                              .btn-add { background-color: #28a745; }
                                                                                                                                .btn-view { background-color: #007bff; }
                                                                                                                                  .btn-admin { background-color: #dc3545; }
                                                                                                                                    .button-area a:hover {
                                                                                                                                        opacity: 0.9;
                                                                                                                                            transform: translateY(-3px);
                                                                                                                                              }
                                                                                                                                                .party-section {
                                                                                                                                                    padding: 40px 0;
                                                                                                                                                      }
                                                                                                                                                        .party-carousel h2 {
                                                                                                                                                            margin-bottom: 20px;
                                                                                                                                                                font-size: 2rem;
                                                                                                                                                                    color: #fff;
                                                                                                                                                                        text-shadow: 1px 1px 2px rgba(0,0,0,0.6);
                                                                                                                                                                          }
                                                                                                                                                                            /* محاذاة محتوى الكاروسيل في الوسط */
                                                                                                                                                                              .party-carousel .carousel-inner {
                                                                                                                                                                                  text-align: center;
                                                                                                                                                                                    }
                                                                                                                                                                                      /* إزالة تغيير العرض الافتراضي لعنصر الكاروسيل */
                                                                                                                                                                                        .party-carousel .carousel-item {
                                                                                                                                                                                            text-align: center;
                                                                                                                                                                                              }
                                                                                                                                                                                                /* ضبط الصور لتكون في المنتصف */
                                                                                                                                                                                                  .party-carousel .carousel-item img {
                                                                                                                                                                                                      display: block;
                                                                                                                                                                                                          margin: 0 auto;
                                                                                                                                                                                                              max-width: 300px;
                                                                                                                                                                                                                  height: 200px;
                                                                                                                                                                                                                      object-fit: cover;
                                                                                                                                                                                                                          border-radius: 10px;
                                                                                                                                                                                                                              transition: transform 0.3s ease, box-shadow 0.3s ease;
                                                                                                                                                                                                                                  box-shadow: 0 4px 12px rgba(0,0,0,0.15);
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                      .party-carousel .carousel-item img:hover {
                                                                                                                                                                                                                                          transform: scale(1.05);
                                                                                                                                                                                                                                              box-shadow: 0 6px 16px rgba(0,0,0,0.25);
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                  @media (max-width: 768px) {
                                                                                                                                                                                                                                                      .hero-section {
                                                                                                                                                                                                                                                            padding: 60px 10px;
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                    .party-carousel .carousel-item img {
                                                                                                                                                                                                                                                                          max-width: 100%;
                                                                                                                                                                                                                                                                                height: 150px;
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                      </style>

                                                                                                                                                                                                                                                                                      <section class="hero-section">
                                                                                                                                                                                                                                                                                        <div class="container hero-content">
                                                                                                                                                                                                                                                                                            <h1>مرحباً بكم في نظام الانتخابات</h1>
                                                                                                                                                                                                                                                                                                <p>نظام متكامل لإدارة المراكز والمحطات مع تتبع الأصوات بسهولة</p>
                                                                                                                                                                                                                                                                                                    <div class="button-area">
                                                                                                                                                                                                                                                                                                          <?php if(isset($_SESSION['account_type'])): ?>

                                                                                                                                                                                                                                                                                                                  <?php if($_SESSION['account_type'] !== 'viewer'): ?>
                                                                                                                                                                                                                                                                                                                            <a href="add_votes.php" class="btn-add">
                                                                                                                                                                                                                                                                                                                                        <i class="fa-solid fa-chart-bar"></i> إدخال الأصوات
                                                                                                                                                                                                                                                                                                                                                  </a>
                                                                                                                                                                                                                                                                                                                                                          <?php endif; ?>

                                                                                                                                                                                                                                                                                                                                                                  <a href="view_votes.php" class="btn-view">
                                                                                                                                                                                                                                                                                                                                                                            <i class="fa-solid fa-eye"></i> عرض الأصوات
                                                                                                                                                                                                                                                                                                                                                                                    </a>

                                                                                                                                                                                                                                                                                                                                                                                            <!-- إضافة زر لوحة التحكّم لجميع المستخدمين -->
                                                                                                                                                                                                                                                                                                                                                                                                    <a href="dashboard.php" class="btn-admin">
                                                                                                                                                                                                                                                                                                                                                                                                              <i class="fa-solid fa-tachometer-alt"></i> لوحة التحكّم
                                                                                                                                                                                                                                                                                                                                                                                                                      </a>

                                                                                                                                                                                                                                                                                                                                                                                                                              <!-- زر أدوات الإدارة للأدمن والوكيل -->
                                                                                                                                                                                                                                                                                                                                                                                                                                      <?php if($_SESSION['account_type'] === 'admin' || $_SESSION['account_type'] === 'agent'): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <a href="admin_tools.php" class="btn-admin">
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <i class="fa-solid fa-user-shield"></i> أدوات الإدارة
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <?php endif; ?>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <section class="party-section">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="container text-center party-carousel">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2>بعض من أعمالنا</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div id="partyCarousel" class="carousel slide" data-bs-ride="carousel" data-bs-interval="4000" data-bs-wrap="true">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div class="carousel-inner">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for($i = 1; $i <= 12; $i++):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $active = ($i == 1) ? "active" : "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $imgPath = "sor/khaleefa{$i}.jpg";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $imgVer = file_exists($imgPath) ? filemtime($imgPath) : time();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div class="carousel-item <?php echo $active; ?>">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <img src="<?php echo $imgPath; ?>?ver=<?php echo $imgVer; ?>" alt="أعمالنا <?php echo $i; ?>">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php endfor; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button class="carousel-control-prev" type="button" data-bs-target="#partyCarousel" data-bs-slide="prev">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span class="visually-hidden">السابق</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button class="carousel-control-next" type="button" data-bs-target="#partyCarousel" data-bs-slide="next">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span class="visually-hidden">التالي</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php include 'footer.php'; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    