<?php
require 'csrf.php'; 
require 'auth.php';
require 'access_control.php';
session_start();
if (!isset($_SESSION['admin_logged_in']) || $_SESSION['admin_logged_in'] !== true) {
    header("Location: admin_login.php");
        exit;
        }
        $pageTitle = "إدارة التصميمات";
        require 'config.php';
        include 'header.php';

        // تعريف التصاميم الـ12 مع إعدادات المعاينة
        $designs = [
            'design1' => [
                    'name' => 'تصميم المكعبات',
                            'bg'   => "linear-gradient(135deg, #000, #fff), url('images/cubes.svg')",
                                    'desc' => "خلفية بمكعبات هندسية بتدرجات أسود وأبيض"
                                        ],
                                            'design2' => [
                                                    'name' => 'التصميم 2',
                                                            'bg'   => "url('images/cyber-data.jpg')"
                                                                ],
                                                                    'design3' => [
                                                                            'name' => 'التصميم 3',
                                                                                    'bg'   => "linear-gradient(135deg, #1e0249, #4b0082, #800080)"
                                                                                        ],
                                                                                            'design4' => [
                                                                                                    'name' => 'التصميم 4',
                                                                                                            'bg'   => "linear-gradient(135deg, #000, #003300, #00cc00)"
                                                                                                                ],
                                                                                                                    'design5' => [
                                                                                                                            'name' => 'التصميم 5',
                                                                                                                                    'bg'   => "linear-gradient(135deg, #000428, #004e92)"
                                                                                                                                        ],
                                                                                                                                            'design6' => [
                                                                                                                                                    'name' => 'التصميم 6',
                                                                                                                                                            'bg'   => "linear-gradient(135deg, #3a3a3a, #bbbbbb)"
                                                                                                                                                                ],
                                                                                                                                                                    'design7' => [
                                                                                                                                                                            'name' => 'التصميم 7',
                                                                                                                                                                                    'bg'   => "repeating-linear-gradient(45deg, #141414, #141414 10px, #1a1a1a 10px, #1a1a1a 20px)"
                                                                                                                                                                                        ],
                                                                                                                                                                                            'design8' => [
                                                                                                                                                                                                    'name' => 'تصميم الأسطوانات',
                                                                                                                                                                                                            'bg'   => "linear-gradient(135deg, #000, #006400), url('images/cylinders.svg')",
                                                                                                                                                                                                                    'desc' => "خلفية بأسطوانات هندسية بتدرجات بين الأسود والأخضر"
                                                                                                                                                                                                                        ],
                                                                                                                                                                                                                            'design9' => [
                                                                                                                                                                                                                                    'name' => 'تصميم الكرات',
                                                                                                                                                                                                                                            'bg'   => "linear-gradient(135deg, #000, #00008b), url('images/circles.svg')",
                                                                                                                                                                                                                                                    'desc' => "خلفية بكرات هندسية بتدرجات بين الأسود والأزرق"
                                                                                                                                                                                                                                                        ],
                                                                                                                                                                                                                                                            'design10' => [
                                                                                                                                                                                                                                                                    'name' => 'التصميم 10',
                                                                                                                                                                                                                                                                            'bg'   => "linear-gradient(135deg, #ff6e7f, #bfe9ff)"
                                                                                                                                                                                                                                                                                ],
                                                                                                                                                                                                                                                                                    'design11' => [
                                                                                                                                                                                                                                                                                            'name' => 'التصميم 11',
                                                                                                                                                                                                                                                                                                    'bg'   => "radial-gradient(circle at 50% 50%, #0f2027, #203a43, #2c5364)"
                                                                                                                                                                                                                                                                                                        ],
                                                                                                                                                                                                                                                                                                            'design12' => [
                                                                                                                                                                                                                                                                                                                    'name' => 'تصميم المعينات والمثلثات',
                                                                                                                                                                                                                                                                                                                            'bg'   => "linear-gradient(135deg, #000, #ff8c00, #00008b, #fff), url('images/stars_triangles.svg')",
                                                                                                                                                                                                                                                                                                                                    'desc' => "خلفية تضم معينات ومثلثات بتدرجات تجمع البرتقالي والأزرق والأسود والأبيض"
                                                                                                                                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                                                                                                                        ];
                                                                                                                                                                                                                                                                                                                                        // استرجاع التصميم الحالي من قاعدة البيانات
                                                                                                                                                                                                                                                                                                                                        $stmt = $pdo->prepare("SELECT setting_value FROM site_settings WHERE setting_key = 'selected_design'");
                                                                                                                                                                                                                                                                                                                                        $stmt->execute();
                                                                                                                                                                                                                                                                                                                                        $selected_design = $stmt->fetchColumn();

                                                                                                                                                                                                                                                                                                                                        // إذا تم إرسال النموذج لتحديث التصميم
                                                                                                                                                                                                                                                                                                                                        if ($_SERVER["REQUEST_METHOD"] === "POST" && isset($_POST['design'])) {
                                                                                                                                                                                                                                                                                                                                            $new_design = $_POST['design'];
                                                                                                                                                                                                                                                                                                                                                $stmt = $pdo->prepare("UPDATE site_settings SET setting_value = ? WHERE setting_key = 'selected_design'");
                                                                                                                                                                                                                                                                                                                                                    if ($stmt->execute([$new_design])) {
                                                                                                                                                                                                                                                                                                                                                            $msg = "تم تحديث التصميم بنجاح.";
                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                        $msg = "حدث خطأ أثناء تحديث التصميم.";
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                header("Location: site_design.php?msg=" . urlencode($msg));
                                                                                                                                                                                                                                                                                                                                                                                    exit;
                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                    ?>
                                                                                                                                                                                                                                                                                                                                                                                    <div class="container my-5">
                                                                                                                                                                                                                                                                                                                                                                                        <h2 class="text-center mb-4">اختيار تصميم الموقع</h2>
                                                                                                                                                                                                                                                                                                                                                                                            <?php if(isset($_GET['msg'])): ?>
                                                                                                                                                                                                                                                                                                                                                                                                  <div class="alert alert-info text-center"><?php echo htmlspecialchars($_GET['msg']); ?></div>
                                                                                                                                                                                                                                                                                                                                                                                                      <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                          <form method="POST">
                                                                                                                                                                                                                                                                                                                                                                                                                <div class="row g-3">
                                                                                                                                                                                                                                                                                                                                                                                                                        <?php foreach($designs as $key => $design): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <div class="col-6 col-md-4 col-lg-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                              <div class="card h-100">
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="card-img-top" style="height: 150px; background: <?php echo $design['bg']; ?>; background-size: <?php echo (in_array($key, ['design1','design8','design9','design12']) ? 'contain' : 'cover'); ?>; background-position: center;"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div class="card-body text-center p-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h6 class="card-title mb-1"><?php echo $design['name']; ?></h6>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <?php if(isset($design['desc'])): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p class="card-text small mb-1"><?php echo $design['desc']; ?></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="form-check">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input class="form-check-input" type="radio" name="design" id="<?php echo $key; ?>" value="<?php echo $key; ?>" <?php echo ($selected_design == $key ? "checked" : ""); ?>>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label class="form-check-label" for="<?php echo $key; ?>">اختر</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php endforeach; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="text-center mt-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button type="submit" class="btn btn-primary btn-custom">تحديث التصميم</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <?php include 'footer.php'; ?>