<?php
require 'csrf.php'; 
require 'auth.php';
require 'access_control.php';
session_start();
if (!isset($_SESSION["admin_logged_in"])) {
    header("Location: admin_login.php");
        exit;
        }
        $pageTitle = "إدارة الموقع";
        require 'config.php';
        include 'header.php';
        ?>
        <style>
          /* تنسيقات إضافية لتحسين تصميم الصفحة مع خلفية شفافة خلف الأزرر */
            .management-card {
                  margin: 40px auto;
                        max-width: 800px;
                              background: transparent;
                                    border-radius: 15px;
                                          box-shadow: 0 8px 16px rgba(0,0,0,0.15);
                                                padding: 30px;
                                                  }
                                                    .management-card h2 {
                                                          font-family: 'Arial', sans-serif;
                                                                font-weight: bold;
                                                                      color: #333;
                                                                            margin-bottom: 30px;
                                                                              }
                                                                                .management-btn {
                                                                                      font-size: 1.1rem;
                                                                                            border-radius: 10px;
                                                                                                  padding: 15px;
                                                                                                        display: flex;
                                                                                                              align-items: center;
                                                                                                                    justify-content: center;
                                                                                                                          transition: all 0.3s ease;
                                                                                                                            }
                                                                                                                              .management-btn i {
                                                                                                                                    margin-left: 10px;
                                                                                                                                          font-size: 1.3rem;
                                                                                                                                            }
                                                                                                                                              .management-btn:hover {
                                                                                                                                                    transform: translateY(-3px);
                                                                                                                                                          box-shadow: 0 4px 12px rgba(0,0,0,0.2);
                                                                                                                                                            }
                                                                                                                                                              .back-btn {
                                                                                                                                                                    margin-top: 25px;
                                                                                                                                                                      }
                                                                                                                                                                      </style>

                                                                                                                                                                      <div class="container">
                                                                                                                                                                        <div class="management-card text-center">
                                                                                                                                                                            <h2>إدارة الموقع</h2>
                                                                                                                                                                                <div class="row g-4">
                                                                                                                                                                                      <div class="col-12 col-md-4">
                                                                                                                                                                                              <a href="site_design.php" class="btn btn-dark management-btn w-100" title="التصميمات">
                                                                                                                                                                                                        التصميمات
                                                                                                                                                                                                                  <i class="fa-solid fa-cog"></i>
                                                                                                                                                                                                                          </a>
                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                      <div class="col-12 col-md-4">
                                                                                                                                                                                                                                              <a href="images_logos.php" class="btn btn-warning management-btn w-100" title="تغيير الشعار والصور">
                                                                                                                                                                                                                                                        تغيير الشعار والصور
                                                                                                                                                                                                                                                                  <i class="fa-solid fa-image"></i>
                                                                                                                                                                                                                                                                          </a>
                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                      <div class="col-12 col-md-4">
                                                                                                                                                                                                                                                                                              <a href="force_logout_all.php" class="btn btn-danger management-btn w-100" title="تهيئة الموقع">
                                                                                                                                                                                                                                                                                                        تهيئة الموقع
                                                                                                                                                                                                                                                                                                                  <i class="fa-solid fa-sign-out-alt"></i>
                                                                                                                                                                                                                                                                                                                          </a>
                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                      <!-- زر التصدير والرفع الجديد -->
                                                                                                                                                                                                                                                                                                                                            <div class="col-12 col-md-4">
                                                                                                                                                                                                                                                                                                                                                    <a href="upload.php" class="btn btn-info management-btn w-100" title="التصدير والرفع">
                                                                                                                                                                                                                                                                                                                                                              <div class="d-flex flex-column align-items-center">
                                                                                                                                                                                                                                                                                                                                                                          <span>التصدير والرفع</span>
                                                                                                                                                                                                                                                                                                                                                                                      <small class="text-white-50">upload.php</small>
                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                          <i class="fa-solid fa-upload"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                  </a>
                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="text-center back-btn">
                                                                                                                                                                                                                                                                                                                                                                                                                                      <a href="admin_tools.php" class="btn btn-secondary management-btn" title="عودة إلى أدوات الإدارة">
                                                                                                                                                                                                                                                                                                                                                                                                                                              العودة إلى أدوات الإدارة
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <i class="fa-solid fa-arrow-left"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <?php include 'footer.php'; ?>