<?php
require 'csrf.php'; 
require 'auth.php';
require 'access_control.php';
session_start();
if (!isset($_SESSION['admin_logged_in']) || $_SESSION['admin_logged_in']!==true) {
    header('Location: admin_login.php');
        exit;
        }
        require 'config.php';
        $pageTitle = 'رفع واستعادة النسخ الاحتياطية';
        include 'header.php';

        $message     = '';
        $statusClass = 'info';

        if ($_SERVER['REQUEST_METHOD']==='POST' && isset($_FILES['backup_file'])) {
            $f = $_FILES['backup_file'];
                if ($f['error']===UPLOAD_ERR_OK && strtolower(pathinfo($f['name'],PATHINFO_EXTENSION))==='zip') {
                        $tmpDir = sys_get_temp_dir().'/restore_'.time();
                                mkdir($tmpDir,0755,true);
                                        // افك الZIP
                                                $zip = new ZipArchive();
                                                        if ($zip->open($f['tmp_name'])===TRUE) {
                                                                    $zip->extractTo($tmpDir);
                                                                                $zip->close();

                                                                                            try {
                                                                                                            // DB أولاً
                                                                                                                            $pdo->exec("SET FOREIGN_KEY_CHECKS=0;");
                                                                                                                                            foreach (glob("$tmpDir/*.sql") as $sql) {
                                                                                                                                                                $pdo->exec(file_get_contents($sql));
                                                                                                                                                                                }
                                                                                                                                                                                                $pdo->exec("SET FOREIGN_KEY_CHECKS=1;");

                                                                                                                                                                                                                // احذف ملفات الموقع الحالي (عدا bk)
                                                                                                                                                                                                                                $root = __DIR__;
                                                                                                                                                                                                                                                foreach (scandir($root) as $item) {
                                                                                                                                                                                                                                                                    if (in_array($item,['.','..','bk',basename(__FILE__)])) continue;
                                                                                                                                                                                                                                                                                        $path = "$root/$item";
                                                                                                                                                                                                                                                                                                            is_dir($path) ? rrmdir($path) : @unlink($path);
                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                            // أنقل كل شيء من tmp إلى جذر الموقع
                                                                                                                                                                                                                                                                                                                                                            rcopy($tmpDir, $root);
                                                                                                                                                                                                                                                                                                                                                                            rrmdir($tmpDir);

                                                                                                                                                                                                                                                                                                                                                                                            $message     = '✔ استعادة كاملة للموقع إلى حالته الأصلية.';
                                                                                                                                                                                                                                                                                                                                                                                                            $statusClass = 'success';
                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (Exception $e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                        $message     = '✖ خطأ أثناء الاستعادة: '.$e->getMessage();
                                                                                                                                                                                                                                                                                                                                                                                                                                                        $statusClass = 'danger';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $message     = '✖ غير قادر على فتح أرشيف ZIP.';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $statusClass = 'danger';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $message     = '✖ الرجاء رفع ملف ZIP صالح.';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $statusClass = 'warning';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // دوال مساعدة لحذف/نسخ recursive
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function rrmdir($d) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        foreach (array_diff(scandir($d),['.','..']) as $f) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $p="$d/$f";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        is_dir($p)?rrmdir($p):@unlink($p);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                @rmdir($d);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function rcopy($s,$d) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $o=opendir($s);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @mkdir($d,0755,true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            while(false!==($f=readdir($o))) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if(in_array($f,['.','..'])) continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $sp="$s/$f"; $dp="$d/$f";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    is_dir($sp)?rcopy($sp,$dp):copy($sp,$dp);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            closedir($o);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php if ($message): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div class="alert alert-<?= $statusClass ?> text-center"><?= $message ?></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <?php endif; ?>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div class="card shadow-sm mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="card-body">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h2 class="card-title text-center mb-3"><i class="fa-solid fa-upload"></i> رفع واستعادة الباكاب</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <form method="post" enctype="multipart/form-data">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input type="file" name="backup_file" class="form-control" accept=".zip" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div class="d-grid gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button type="submit" class="btn btn-primary btn-custom">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <i class="fa-solid fa-rotate"></i> استعادة النسخة
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?php include 'footer.php'; ?>